### ISSUE TITLE
Framework 4.8 ClickOnce Runtime Failure

### ISSUE THREAD

**Issue by bensmooth** [desjarlais/Scintilla.NET#138]
**Describe the bug**
The type initializer for 'ScintillaNET.Scintilla' threw an exception.
Inner exception:Scintilla.NET satellite assemblies not found in C:\Users\<snip>\AppData\Local\Apps\2.0\<snip>\x64

**To Reproduce**
ClickOnce deployment of .NET Framework 4.8 x64 app.  

**Expected behavior**
It works as expected in a local build, but not when the app is installed through ClickOnce.

I can see that in the local build, the x64 folder is present and contains Lexilla.dll and Scintilla.dll.  In the ClickOnce installation location, the Dlls are not present in the x64 folder.

**Desktop**
 - OS: Windows 10 Version 22H2
 - .NET Framework 4.8
 - Scintilla.NET Version 5.3.2.9

By opening up the nuget package, I can see that I have the fix from #117.

**Comment by ahmetsait** [comment]
This is fixed in [v5.4.0](https://github.com/desjarlais/Scintilla.NET/releases/tag/v5.4.0), not v5.3.2.9.

**Comment by bensmooth** [comment]
My fault - I accidentally installed Scintilla.NET rather than Scintilla5.NET thinking it was the latest.  If there is continuity between this project and the original, maybe the older package should be marked as deprecated to encourage people to not use it.

Anyways, I'm still seeing problems with ClickOnce deployment after upgrading to:
```
<PackageReference Include="Scintilla5.NET" Version="5.6.1" />
```

The path it is searching in is slightly different:
```
The type initializer for 'ScintillaNET.Scintilla' threw an exception.

Inner exception:Scintilla.NET satellite assemblies not found in any of the following paths:
C:\Users\<snip>\AppData\Local\Apps\2.0\<snip>\runtimes\win-x64\native

Inner callstack:
   at ScintillaNET.Scintilla..cctor()
```

the `runtimes\win-x64\native` path exists in the clickonce install, but Lexilla.dll and Scintilla.dll are missing.  

Everything still works as expected in a local build.

**Comment by ahmetsait** [comment]
Still cannot reproduce with a fresh .NET 4.8 project. ClickOnce works just fine on my end.
![image](https://github.com/user-attachments/assets/52fe9f92-b119-43c5-87a3-2b9d4c72a875)
